site_name: J-Node 的极客世界  # 以后可以在这里改名
site_url: https://example.com

# 1. 主题配置：使用 Material 主题
theme:
  name: material
  language: zh          # <--- 这里改成 zh
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs     # 启用顶部导航栏 (适合博客)
    - navigation.top      # 返回顶部按钮
    - search.suggest      # 搜索建议
    - content.code.copy   # 代码块右上角的一键复制按钮

# 2. 插件配置
plugins:
  - search                # 启用搜索

# 3. Markdown 扩展功能 (CS学生必备)
markdown_extensions:
  - pymdownx.highlight:   # 代码高亮
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  # 支持复杂的代码块嵌套
  - admonition            # 支持漂亮的提示框 (!!! note)
  - pymdownx.arithmatex:  # 支持 LaTeX 数学公式
      generic: true

# 4. 数学公式支持 (MathJax)
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 5. 导航栏结构 (你可以手动指定，如果不写这一块，它会自动读取文件夹)
nav:
  - 首页: index.md
  - j-node精选文章: my-first-post.md
